version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

  go-coinbase-dca:
    container_name: go-coinbase-dca
    build:
      context: .
    depends_on:
      - "postgres"

volumes:
  dbdata: 
            